### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by bradenhelmer** [NCSU-CSC510-Group-BHAKQH/URL-Shortner#22]
All of the new features will need some amount of tests added for show in the project turn in.

- Phishing protection #10 
- Stats page updates #13 #15 
- Location and browser insights #14 
- Map view #20 

Refer to closed pull requests above to see what new code needs to be covered.

**Comment by hunglequoc2001** [comment]
I'm working on it

**Comment by bradenhelmer** [comment]
> I'm working on it

Cool, make sure to use the `22-tests` branch.
